# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
plugins: ['jekyll/scholar']
title: McCrone Lab
name: JT McCrone
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Virus evolution and phylodynamcis at the Fred Hutch.
baseurl: "" # the subpath of your site, e.g. /blog
url: "htts://mccronelab.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  mccronelab
repository: mccronelab/site

logo: assets/images/McCrone_Lab_Logo_3_grey.png

atom_feed:
  hide: true

masthead_title: "McCrone Lab"



# Build settings
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed

collections_dir: collections

collections:
  people:
    output: true
  news:
    output: true
    
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      comments: true
      share: true
      related: true

scholar:
  style: apa
  locale: en

  sort_by: year
  order: descending

  group_by: year
  group_order: descending

  source: ./_bibliography
  bibliography: collapsed.bib
  bibliography_template: "{{ reference | replace_first: 'McCrone, J. T.', '<b>McCrone, J. T.</b>'| replace_first: 'McCrone*, J. T.', '<b>McCrone*, J. T.</b>' |replace_first: 'McCrone, J.', '<b>McCrone, J.</b>'}}"

  replace_strings: true
  join_strings:    true

  use_raw_bibtex_entry: false

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
